### ISSUE TITLE
Wrong types information in `package.json`

### ISSUE THREAD

**Issue by peterblazejewicz** [ProseMirror/prosemirror-test-builder#8]
Hey folks,
AFAIK the package does not distribute declaration types, contrary to entry in `package.json`:
https://github.com/ProseMirror/prosemirror-test-builder/blob/master/package.json#L8
this can lead to issues when TS automatic types acquisition feature is being used by users.
There is existing @types/prosemirror-test-builder at the same time.
What's the source of the truth for typings?
https://www.npmjs.com/package/@types/prosemirror-test-builder
Thanks!

**Comment by marijnh** [comment]
Which version of the package are you referring to? The regular versions should have neither a `types` entry nor a .d.ts file, and the current beta version should have both.

**Comment by peterblazejewicz** [comment]
I'm really sorry for not being specific. I meant 1.0.6, but now realized I missed the point (and the correct version as you pointed). Sorry for the noise :)
